---
name: homestead
version: "{{major}}.{{minor}}.{{patch}}"
description: A repository for last-mile home automation integration.

requirements:
  - aiofiles
  - runtimepy>=4.4.5

dev_requirements:
  - circup

mypy_local: |
  [mypy-aiofiles.*]
  ignore_missing_imports = True
