---
name: homestead
version: "{{major}}.{{minor}}.{{patch}}"
description: A repository for last-mile home automation integration.

requirements:
  - runtimepy>=5.7.10

dev_requirements:
  - Adafruit-Blinka
  - circup

mypy_local: |
  [mypy-aiofiles.*]
  ignore_missing_imports = True
