---
includes_left:
  - package://runtimepy/server.yaml
includes:
  - linux.yaml

factories:
  - {name: homestead.libre_embedded.null.NullStruct}
structs:
  - {name: "null", factory: NullStruct}

port_overrides:
  runtimepy_http_server: 8000
app:
  - runtimepy.net.apps.wait_for_stop
